In [1]:
print("Hello World")

Hello World

**Step 1 Data Exploration & Leading**

In [104]:
#importing dependencies
import pandas as pd

#mysql toolkit
import pymysql #this will work as adapter
from sqlalchemy import create_engine
#psql
import psycopg2

In [105]:
df = pd.read_csv(r'C:\Users\pradh\OneDrive\Documents\Desktop\Walmart_Analysis\Walmart.csv', encoding_errors='ignore')

df.shape

(10051, 11)

In [106]:
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,$46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,$58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,$86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [107]:
df.describe()

         invoice_id      quantity        rating  profit_margin
count  10051.000000  10020.000000  10051.000000   10051.000000
mean    5025.741220      2.353493      5.825659       0.393791
std     2901.174372      1.602658      1.763991       0.090669
min        1.000000      1.000000      3.000000       0.180000
25%     2513.500000      1.000000      4.000000       0.330000
50%     5026.000000      2.000000      6.000000       0.330000
75%     7538.500000      3.000000      7.000000       0.480000
max    10000.000000     10.000000     10.000000       0.570000

In [108]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10051 entries, 0 to 10050
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10051 non-null  int64
 1   Branch          10051 non-null  str
 2   City            10051 non-null  str
 3   category        10051 non-null  str
 4   unit_price      10020 non-null  str
 5   quantity        10020 non-null  float64
 6   date            10051 non-null  str
 7   time            10051 non-null  str
 8   payment_method  10051 non-null  str
 9   rating          10051 non-null  float64
 10  profit_margin   10051 non-null  float64
dtypes: float64(3), int64(1), str(7)
memory usage: 863.9 KB

In [109]:
df.duplicated().sum()

np.int64(51)

In [110]:
df.drop_duplicates(inplace=True)
df.duplicated().sum()

np.int64(0)

In [111]:
df.isnull().sum()

invoice_id         0
Branch             0
City               0
category           0
unit_price        31
quantity          31
date               0
time               0
payment_method     0
rating             0
profit_margin      0
dtype: int64

In [112]:
#dropping all rows with missing records
df.dropna(inplace=True)

In [113]:
df.shape

(9969, 11)

In [114]:
df.dtypes

invoice_id          int64
Branch                str
City                  str
category              str
unit_price            str
quantity          float64
date                  str
time                  str
payment_method        str
rating            float64
profit_margin     float64
dtype: object

In [24]:
df['unit_price'].astype(float)

ValueError: could not convert string to float: '$74.69'

In [115]:
df['unit_price']=df['unit_price'].str.replace('$','').astype(float)
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [116]:
df.dtypes

invoice_id          int64
Branch                str
City                  str
category              str
unit_price        float64
quantity          float64
date                  str
time                  str
payment_method        str
rating            float64
profit_margin     float64
dtype: object

In [117]:
df.columns

Index(['invoice_id', 'Branch', 'City', 'category', 'unit_price', 'quantity',
       'date', 'time', 'payment_method', 'rating', 'profit_margin'],
      dtype='str')

In [127]:
df.columns = df.columns.str.lower()
df.columns

Index(['invoice_id', 'branch', 'city', 'category', 'unit_price', 'quantity',
       'date', 'time', 'payment_method', 'rating', 'profit_margin', 'total'],
      dtype='str')

In [119]:
df['total'] = df['unit_price'] * df['quantity']
df.head()

,invoice_id,branch,city,category,unit_price,quantity,date,time,payment_method,rating,profit_margin,total
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48,522.83
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48,76.40
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33,324.31
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33,465.76
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48,604.17

In [ ]:
#mysql
#host = localhost
#port = 3306
#user = root
#password='Manorama@2003'

#psql
#host = localhost
#port = 5432
#user = -0stgres
#password='Manorama@2003'

In [120]:
df.shape

(9969, 12)

In [121]:
df.to_csv('walmart_clean_data.csv', index=False)

In [122]:
#mysql connection

engine_mysql = create_engine(
"mysql+pymysql://root:Manorama%402003@localhost:3306/walmart_db"
)

try:
    conn = engine_mysql.connect()
    print("Connection successful")
    conn.close()
except Exception as e:
    print("Connection failed")
    print(e)

Connection successful

In [123]:
df.to_sql(name='walmart', con=engine_mysql, if_exists='replace', index=False)

9969

In [124]:
#psql connection
# "mysql+pymysql://user:password@localhost:3306/db_name"
engine_psql = create_engine("postgresql+psycopg2://postgres:Manorama%402003@localhost:5432/walmart_db")

try:
    engine_psql
    print("Connection Successed to PSQL")
except:
    print("Unable to connect")

Connection Successed to PSQL

In [128]:
df.to_sql(
    name='walmart',
    con=engine_psql,
    if_exists='replace',
    index=False
)

969

In [126]:
df.to_csv('walmart_clean_data.csv', index=False)